### ISSUE TITLE
Clarification on AddNode

### ISSUE THREAD

**Issue by 89z** [stevenle/topsort#5]
I am trying to use topsort with the output from Golang callgraph [1], which is like this:

~~~
"prog/test.A" "prog/test.C"
"prog/test.A" "prog/test.D"
"prog/test.main" "prog/test.A"
"prog/test.B" "prog/test.E"
"prog/test.B" "prog/test.F"
"prog/test.main" "prog/test.B"
~~~

As a test, I can use this program and it works as expected:

~~~go
package main

import (
   "fmt"
   "github.com/stevenle/topsort"
)

func main() {
   graph := topsort.NewGraph()
   graph.AddNode("main")
   graph.AddNode("A")
   graph.AddNode("B")
   graph.AddEdge("main", "A")
   graph.AddEdge("A", "B")
   s, e := graph.TopSort("main")
   if e != nil {
      panic(e)
   }
   fmt.Println(s)
}
~~~

However, I am not going to know all the nodes until the end, so I tried this as well:

~~~go
graph.AddNode("main")
graph.AddNode("A")
graph.AddEdge("main", "A")

graph.AddNode("A")
graph.AddNode("B")
graph.AddEdge("A", "B")
~~~

and it seems to work fine, even though I added a node twice. My question is, what is the point of `AddNode`? With most DAG input I have seen, you dont get a listing of the nodes, but just a listing of edges. So isnt `AddNode` redundant, or something that could be processed internally?

1. https://github.com/golang/tools/tree/master/cmd/callgraph

**Comment by stevenle** [comment]
This was written 8 yrs ago so I can't remember exactly why I had wanted the AddNode() calls to be explicit but I agree with you that the API would be simpler just being able to specify the edges. I just pushed up `v0.2.0` which should fix this, let me know if any issues.
