### ISSUE TITLE
thanks for the module! you should release the generic version

### ISSUE THREAD

**Issue by tonymet** [stevenle/topsort#7]
Hey man thanks again. I used your module during [Advent of Code 2024 D5 ](https://github.com/tonymet/aoc2020/blob/master/aoc2024/d5/main.go#L44)

You should tag/release the generic version. it seems to work well. I saw that you mentioned it was an early experiment. it's still working great!

Thanks again for the module.

**Comment by stevenle** [comment]
@tonymet thanks for pointing to advent of code, seems like fun. tried out the first 3 problems this morning (https://github.com/stevenle/advent-2024), having a good time so far.

re: releasing the generic version, i'm happy to do that, does it just need a git tag? i created this repo about 10 years ago when i was doing more experimental golang stuff, but i've almost completely switched to typescript now so my familiarity with go isn't very up-to-date.

**Comment by tonymet** [comment]
so glad to hear it. yeah just the tag `v0.3.0` should do it. I'm happy to test out the import and get it linked to https://pkg.go.dev/ for you.

**Comment by stevenle** [comment]
@tonymet just tagged `v0.3.0`: https://github.com/stevenle/topsort/releases/tag/v0.3.0

lmk if that worked.

**Comment by tonymet** [comment]
i spoke too soon.  One of these should work. 

**A)** use `v2.0.1` (major version has to match the `/v2` in your mod name  . OR...

**B)** drop the module version e.g. 

```
--- a/go.mod
+++ b/go.mod
@@ -1,3 +1,3 @@
-module github.com/stevenle/topsort/v2
+module github.com/stevenle/topsort

 go 1.18
```

i got this error due to the mismatch 
```
 go get github.com/stevenle/topsort/v2@v0.3.0
go: github.com/stevenle/topsort/v2@v0.3.0: invalid version: module path includes a major version suffix, so major version must match
```

**Comment by tonymet** [comment]
here's a trick to speed up testing locally too 
```
mkdir topsort-import ; cd topsort-import
 go mod init
 go mod edit --replace=github.com/stevenle/topstort=$HOME/projects/topsort
 go get github.com/stevenle/topsort@v2.0.1
# make edits and set the module name
# push stevenle/topsort from the module dir
# remove for final testing
go mod edit --dropreplace=github.com/stevenle/topstort
```

**Comment by stevenle** [comment]
@tonymet sorry for delay, i just pushed
https://github.com/stevenle/topsort/releases/tag/v2.0.0

since `v2.0.0` didn't exist yet i went ahead and chose that but if you think `v2.0.1` is needed let me know.

**Comment by tonymet** [comment]
thanks that worked (note the `topsort/v2` path)

```
 go get github.com/stevenle/topsort/v2@v2.0.0
go: downloading github.com/stevenle/topsort/v2 v2.0.0
go: added github.com/stevenle/topsort/v2 v2.0.0
```

**Comment by tonymet** [comment]
and it looks like the module had already been published to [go.dev](https://pkg.go.dev/github.com/stevenle/topsort/v2)

**Comment by tonymet** [comment]
looks like we fixed this one. thanks again for the module and I'm glad you're enjoying AOC

**Comment by stevenle** [comment]
thanks for the confirmation!
